-- Accounts + sync schema.
--
-- Portability notes: plain tables, TIMESTAMPTZ, TEXT keys. The only
-- Postgres-specific piece is the shared `sync_version` sequence that backs
-- the monotonic sync cursor; on SQLite this becomes an INTEGER PRIMARY KEY
-- AUTOINCREMENT on a global counter table.

-- IDs are UUIDs generated by the application (no pgcrypto dependency).

CREATE TABLE users (
    id          UUID PRIMARY KEY,
    email       TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Refresh tokens are stored hashed (SHA-256 of the opaque token) and can be
-- revoked individually (logout) or in bulk (per user). Rotation links the
-- replacement token to its predecessor for reuse detection.
CREATE TABLE refresh_tokens (
    id          UUID PRIMARY KEY,
    user_id     UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash  TEXT NOT NULL UNIQUE,
    expires_at  TIMESTAMPTZ NOT NULL,
    revoked_at  TIMESTAMPTZ,
    rotated_from UUID REFERENCES refresh_tokens(id) ON DELETE SET NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX refresh_tokens_user_idx ON refresh_tokens (user_id);

-- One row per (user, track). `liked = false` rows are tombstones: they are
-- kept (never hard-deleted) so unlikes propagate to offline devices.
-- `version` comes from a global sequence so every write — on any track —
-- advances the per-user sync cursor monotonically.
CREATE SEQUENCE sync_version_seq;

CREATE TABLE likes (
    user_id     UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    track_id    TEXT NOT NULL,
    liked       BOOLEAN NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL,
    version     BIGINT NOT NULL DEFAULT nextval('sync_version_seq'),
    title       TEXT NOT NULL DEFAULT '',
    artist      TEXT NOT NULL DEFAULT '',
    album       TEXT NOT NULL DEFAULT '',
    cover       TEXT NOT NULL DEFAULT '',
    PRIMARY KEY (user_id, track_id)
);
CREATE INDEX likes_user_track_idx ON likes (user_id, track_id);
CREATE INDEX likes_cursor_idx ON likes (user_id, version);
